### ISSUE TITLE
Move to i3 github organization

### ISSUE THREAD

**Issue by acrisci** [i3/AnyEvent-I3#1]
I had to do a bit of searching to find this.

Is this the official repo for this? Should we move it to the github.com/i3 organization?

**Comment by stapelberg** [comment]
An argument for moving the repository would be that i3 prominently uses this module in its test suite.

@airblader, how do you feel about that? Would you think it makes sense to move this repository to i3?

**Comment by Airblader** [comment]
Yeah, I think that makes perfect sense. It's specific to i3 and actually used by i3, I think it belongs in the i3 organization.

**Comment by stapelberg** [comment]
This is now done.
